// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LoadStatus.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_LOADSTATUS_H_
#define _FAST_DDS_GENERATED_LOADSTATUS_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LoadStatus_SOURCE)
#define LoadStatus_DllAPI __declspec( dllexport )
#else
#define LoadStatus_DllAPI __declspec( dllimport )
#endif // LoadStatus_SOURCE
#else
#define LoadStatus_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LoadStatus_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure LoadStatus defined by the user in the IDL file.
 * @ingroup LOADSTATUS
 */
class LoadStatus
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LoadStatus();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LoadStatus();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LoadStatus that will be copied.
     */
    eProsima_user_DllExport LoadStatus(
            const LoadStatus& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LoadStatus that will be copied.
     */
    eProsima_user_DllExport LoadStatus(
            LoadStatus&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LoadStatus that will be copied.
     */
    eProsima_user_DllExport LoadStatus& operator =(
            const LoadStatus& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LoadStatus that will be copied.
     */
    eProsima_user_DllExport LoadStatus& operator =(
            LoadStatus&& x);

    /*!
     * @brief Comparison operator.
     * @param x LoadStatus object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LoadStatus& x) const;

    /*!
     * @brief Comparison operator.
     * @param x LoadStatus object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LoadStatus& x) const;

    /*!
     * @brief This function sets a value in member payloadActive
     * @param _payloadActive New value for member payloadActive
     */
    eProsima_user_DllExport void payloadActive(
            bool _payloadActive);

    /*!
     * @brief This function returns the value of member payloadActive
     * @return Value of member payloadActive
     */
    eProsima_user_DllExport bool payloadActive() const;

    /*!
     * @brief This function returns a reference to member payloadActive
     * @return Reference to member payloadActive
     */
    eProsima_user_DllExport bool& payloadActive();

    /*!
     * @brief This function sets a value in member commsActive
     * @param _commsActive New value for member commsActive
     */
    eProsima_user_DllExport void commsActive(
            bool _commsActive);

    /*!
     * @brief This function returns the value of member commsActive
     * @return Value of member commsActive
     */
    eProsima_user_DllExport bool commsActive() const;

    /*!
     * @brief This function returns a reference to member commsActive
     * @return Reference to member commsActive
     */
    eProsima_user_DllExport bool& commsActive();

    /*!
     * @brief This function sets a value in member thermalActive
     * @param _thermalActive New value for member thermalActive
     */
    eProsima_user_DllExport void thermalActive(
            bool _thermalActive);

    /*!
     * @brief This function returns the value of member thermalActive
     * @return Value of member thermalActive
     */
    eProsima_user_DllExport bool thermalActive() const;

    /*!
     * @brief This function returns a reference to member thermalActive
     * @return Reference to member thermalActive
     */
    eProsima_user_DllExport bool& thermalActive();

    /*!
     * @brief This function sets a value in member timestamp_us
     * @param _timestamp_us New value for member timestamp_us
     */
    eProsima_user_DllExport void timestamp_us(
            uint64_t _timestamp_us);

    /*!
     * @brief This function returns the value of member timestamp_us
     * @return Value of member timestamp_us
     */
    eProsima_user_DllExport uint64_t timestamp_us() const;

    /*!
     * @brief This function returns a reference to member timestamp_us
     * @return Reference to member timestamp_us
     */
    eProsima_user_DllExport uint64_t& timestamp_us();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const LoadStatus& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    bool m_payloadActive;
    bool m_commsActive;
    bool m_thermalActive;
    uint64_t m_timestamp_us;
};

#endif // _FAST_DDS_GENERATED_LOADSTATUS_H_