#pragma once

#include <vector>
#include "LocalSensorHealthStatus.hpp"

namespace core {
    /**
     * @brief SensorHealthStatus
     *
     * @details
     * Consolidated health status across multiple sensors.
     * Generated by SensorHealthManager for consumption by PowerManager.
     */
    struct SensorHealthStatus {
        bool anyDegraded;           // True if any sensor is degraded
        bool anyFailed;             // True if any sensor has failed
        uint64_t timestamp_us;      // Timestamp in microseconds
    };
};